<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170826133851 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE dasoe_simpleteaser_domain_model_teaser (persistence_object_identifier VARCHAR(40) NOT NULL, image VARCHAR(40) DEFAULT NULL, header VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, linkto VARCHAR(255) NOT NULL, border TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_7459D706C53D045F (image), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE dasoe_simpleteaser_domain_model_teaser ADD CONSTRAINT FK_7459D706C53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)');
        $this->addSql('DROP TABLE oe_simpleteasertest_domain_model_teaser');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE oe_simpleteasertest_domain_model_teaser (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, image VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, header VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, text VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, link VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, border TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_B3337B19C53D045F (image), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE oe_simpleteasertest_domain_model_teaser ADD CONSTRAINT FK_B3337B19C53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)');
        $this->addSql('DROP TABLE dasoe_simpleteaser_domain_model_teaser');
    }
}