<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180206193129 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_user DROP INDEX userid, ADD UNIQUE INDEX flow_identity_loveprototo_site_domain_model_user (userid)');
        $this->addSql('DROP INDEX userid_2 ON loveprototo_site_domain_model_user');
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_user CHANGE userid userid INT(11) NOT NULL AUTO_INCREMENT UNIQUE, CHANGE isnew isnew TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_userlike RENAME INDEX idx_73c97d4fac6340b3 TO IDX_73C97D4F2189B29F');
        $this->addSql('DROP INDEX sourceuripathhash ON neos_redirecthandler_databasestorage_domain_model_redirect');
        $this->addSql('ALTER TABLE typo3_media_domain_model_thumbnail RENAME INDEX originalasset_configurationhash TO UNIQ_B7CE141455FF41717F7CBA1A');
        $this->addSql('DROP INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_user CHANGE userid userid INT AUTO_INCREMENT NOT NULL, CHANGE isnew isnew TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX userid_2 ON loveprototo_site_domain_model_user (userid)');
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_user RENAME INDEX flow_identity_loveprototo_site_domain_model_user TO userid');
        $this->addSql('ALTER TABLE loveprototo_site_domain_model_userlike RENAME INDEX idx_73c97d4f2189b29f TO IDX_73C97D4FAC6340B3');
        $this->addSql('CREATE INDEX sourceuripathhash ON neos_redirecthandler_databasestorage_domain_model_redirect (sourceuripathhash, host)');
        $this->addSql('ALTER TABLE typo3_media_domain_model_thumbnail RENAME INDEX uniq_b7ce141455ff41717f7cba1a TO originalasset_configurationhash');
        $this->addSql('CREATE INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event (documentnodeidentifier)');
    }
}